export default [
    {
        value:'CDB',
        name:'国家开发银行'
    },
    {
        value:'ICBC',
        name:'中国工商银行'
    },
    {
        value:'ABC',
        name:'中国农业银行'
    },
    {
        value:'BOC',
        name:'中国银行'
    },
    {
        value:'CCB',
        name:'中国建设银行'
    },
    {
        value:'PSBC',
        name:'中国邮政储蓄银行'
    },
    {
        value:'COMM',
        name:'交通银行'
    },
    {
        value:'CMB',
        name:'招商银行'
    },
    {
        value:'SPDB',
        name:'上海浦东发展银行'
    },
    {
        value:'CIB',
        name:'兴业银行'
    },
    {
        value:'HXBANK',
        name:'华夏银行'
    },
    {
        value:'GDB',
        name:'广东发展银行'
    },
    {
        value:'CMBC',
        name:'中国民生银行'
    },
    {
        value:'CITIC',
        name:'中信银行'
    },
    {
        value:'CEB',
        name:'中国光大银行'
    },
    {
        value:'EGBANK',
        name:'恒丰银行'
    },
    {
        value:'CZBANK',
        name:'浙商银行'
    },
    {
        value:'BOHAIB',
        name:'渤海银行'
    },
    {
        value:'SPABANK',
        name:'平安银行'
    },
    {
        value:'SHRCB',
        name:'上海农村商业银行'
    },
    {
        value:'YXCCB',
        name:'玉溪市商业银行'
    },
    {
        value:'YDRCB',
        name:'尧都农商行'
    },
    {
        value:'BJBANK',
        name:'北京银行'
    },
    {
        value:'SHBANK',
        name:'上海银行'
    },
    {
        value:'JSBANK',
        name:'江苏银行'
    },
    {
        value:'HZCB',
        name:'杭州银行'
    },
    {
        value:'NJCB',
        name:'南京银行'
    },
    {
        value:'NBBANK',
        name:'宁波银行'
    },
    {
        value:'HSBANK',
        name:'徽商银行'
    },
    {
        value:'CSCB',
        name:'长沙银行'
    },
    {
        value:'CDCB',
        name:'成都银行'
    },
    {
        value:'CQBANK',
        name:'重庆银行'
    },
    {
        value:'DLB',
        name:'大连银行'
    },
    {
        value:'NCB',
        name:'南昌银行'
    },
    {
        value:'FJHXBC',
        name:'福建海峡银行'
    },
    {
        value:'HKB',
        name:'汉口银行'
    },
    {
        value:'WZCB',
        name:'温州银行'
    },
    {
        value:'QDCCB',
        name:'青岛银行'
    },
    {
        value:'TZCB',
        name:'台州银行'
    },
    {
        value:'JXBANK',
        name:'嘉兴银行'
    },
    {
        value:'CSRCB',
        name:'常熟农村商业银行'
    },
    {
        value:'NHB',
        name:'南海农村信用联社'
    },
    {
        value:'CZRCB',
        name:'常州农村信用联社'
    },
    {
        value:'H3CB',
        name:'内蒙古银行'
    },
    {
        value:'SXCB',
        name:'绍兴银行'
    },
    {
        value:'SDEB',
        name:'顺德农商银行'
    },
    {
        value:'WJRCB',
        name:'吴江农商银行'
    },
    {
        value:'ZBCB',
        name:'齐商银行'
    },
    {
        value:'GYCB',
        name:'贵阳市商业银行'
    },
    {
        value:'ZYCBANK',
        name:'遵义市商业银行'
    },
    {
        value:'HZCCB',
        name:'湖州市商业银行'
    },
    {
        value:'DAQINGB',
        name:'龙江银行'
    },
    {
        value:'JINCHB',
        name:'晋城银行JCBANK'
    },
    {
        value:'ZJTLCB',
        name:'浙江泰隆商业银行'
    },
    {
        value:'GDRCC',
        name:'广东省农村信用社联合社'
    },
    {
        value:'DRCBCL',
        name:'东莞农村商业银行'
    },
    {
        value:'MTBANK',
        name:'浙江民泰商业银行'
    },
    {
        value:'GCB',
        name:'广州银行'
    },
    {
        value:'LYCB',
        name:'辽阳市商业银行'
    },
    {
        value:'JSRCU',
        name:'江苏省农村信用联合社'
    },
    {
        value:'LANGFB',
        name:'廊坊银行'
    },
    {
        value:'CZCB',
        name:'浙江稠州商业银行'
    },
    {
        value:'DYCB',
        name:'德阳商业银行'
    },
    {
        value:'JZBANK',
        name:'晋中市商业银行'
    },
    {
        value:'BOSZ',
        name:'苏州银行'
    },
    {
        value:'GLBANK',
        name:'桂林银行'
    },
    {
        value:'URMQCCB',
        name:'乌鲁木齐市商业银行'
    },
    {
        value:'CDRCB',
        name:'成都农商银行'
    },
    {
        value:'ZRCBANK',
        name:'张家港农村商业银行'
    },
    {
        value:'BOD',
        name:'东莞银行'
    },
    {
        value:'LSBANK',
        name:'莱商银行'
    },
    {
        value:'BJRCB',
        name:'北京农村商业银行'
    },
    {
        value:'TRCB',
        name:'天津农商银行'
    },
    {
        value:'SRBANK',
        name:'上饶银行'
    },
    {
        value:'FDB',
        name:'富滇银行'
    },
    {
        value:'CRCBANK',
        name:'重庆农村商业银行'
    },
    {
        value:'ASCB',
        name:'鞍山银行'
    },
    {
        value:'NXBANK',
        name:'宁夏银行'
    },
    {
        value:'BHB',
        name:'河北银行'
    },
    {
        value:'HRXJB',
        name:'华融湘江银行'
    },
    {
        value:'ZGCCB',
        name:'自贡市商业银行'
    },
    {
        value:'YNRCC',
        name:'云南省农村信用社'
    },
    {
        value:'JLBANK',
        name:'吉林银行'
    },
    {
        value:'DYCCB',
        name:'东营市商业银行'
    },
    {
        value:'KLB',
        name:'昆仑银行'
    },
    {
        value:'ORBANK',
        name:'鄂尔多斯银行'
    },
    {
        value:'XTB',
        name:'邢台银行'
    },
    {
        value:'JSB',
        name:'晋商银行'
    },
    {
        value:'TCCB',
        name:'天津银行'
    },
    {
        value:'BOYK',
        name:'营口银行'
    },
    {
        value:'JLRCU',
        name:'吉林农信'
    },
    {
        value:'SDRCU',
        name:'山东农信'
    },
    {
        value:'XABANK',
        name:'西安银行'
    },
    {
        value:'HBRCU',
        name:'河北省农村信用社'
    },
    {
        value:'NXRCU',
        name:'宁夏黄河农村商业银行'
    },
    {
        value:'GZRCU',
        name:'贵州省农村信用社'
    },
    {
        value:'FXCB',
        name:'阜新银行'
    },
    {
        value:'HBHSBANK',
        name:'湖北银行黄石分行'
    },
    {
        value:'ZJNX',
        name:'浙江省农村信用社联合社'
    },
    {
        value:'XXBANK',
        name:'新乡银行'
    },
    {
        value:'HBYCBANK',
        name:'湖北银行宜昌分行'
    },
    {
        value:'LSCCB',
        name:'乐山市商业银行'
    },
    {
        value:'TCRCB',
        name:'江苏太仓农村商业银行'
    },
    {
        value:'BZMD',
        name:'驻马店银行'
    },
    {
        value:'GZB',
        name:'赣州银行'
    },
    {
        value:'WRCB',
        name:'无锡农村商业银行'
    },
    {
        value:'BGB',
        name:'广西北部湾银行'
    },
    {
        value:'GRCB',
        name:'广州农商银行'
    },
    {
        value:'JRCB',
        name:'江苏江阴农村商业银行'
    },
    {
        value:'BOP',
        name:'平顶山银行'
    },
    {
        value:'TACCB',
        name:'泰安市商业银行'
    },
    {
        value:'CGNB',
        name:'南充市商业银行'
    },
    {
        value:'CCQTGB',
        name:'重庆三峡银行'
    },
    {
        value:'XLBANK',
        name:'中山小榄村镇银行'
    },
    {
        value:'HDBANK',
        name:'邯郸银行'
    },
    {
        value:'KORLABANK',
        name:'库尔勒市商业银行'
    },
    {
        value:'BOJZ',
        name:'锦州银行'
    },
    {
        value:'QLBANK',
        name:'齐鲁银行'
    },
    {
        value:'BOQH',
        name:'青海银行'
    },
    {
        value:'YQCCB',
        name:'阳泉银行'
    },
    {
        value:'SJBANK',
        name:'盛京银行'
    },
    {
        value:'FSCB',
        name:'抚顺银行'
    },
    {
        value:'ZZBANK',
        name:'郑州银行'
    },
    {
        value:'SRCB',
        name:'深圳农村商业银行'
    },
    {
        value:'BANKWF',
        name:'潍坊银行'
    },
    {
        value:'JJBANK',
        name:'九江银行'
    },
    {
        value:'JXRCU',
        name:'江西省农村信用'
    },
    {
        value:'HNRCU',
        name:'河南省农村信用'
    },
    {
        value:'GSRCU',
        name:'甘肃省农村信用'
    },
    {
        value:'SCRCU',
        name:'四川省农村信用'
    },
    {
        value:'GXRCU',
        name:'广西省农村信用'
    },
    {
        value:'SXRCCU',
        name:'陕西信合'
    },
    {
        value:'WHRCB',
        name:'武汉农村商业银行'
    },
    {
        value:'YBCCB',
        name:'宜宾市商业银行'
    },
    {
        value:'KSRB',
        name:'昆山农村商业银行'
    },
    {
        value:'SZSBK',
        name:'石嘴山银行'
    },
    {
        value:'HSBK',
        name:'衡水银行'
    },
    {
        value:'XYBANK',
        name:'信阳银行'
    },
    {
        value:'NBYZ',
        name:'鄞州银行'
    },
    {
        value:'ZJKCCB',
        name:'张家口市商业银行'
    },
    {
        value:'XCYH',
        name:'许昌银行'
    },
    {
        value:'JNBANK',
        name:'济宁银行'
    },
    {
        value:'CBKF',
        name:'开封市商业银行'
    },
    {
        value:'WHCCB',
        name:'威海市商业银行'
    },
    {
        value:'HBC',
        name:'湖北银行'
    },
    {
        value:'BOCD',
        name:'承德银行'
    },
    {
        value:'BODD',
        name:'丹东银行'
    },
    {
        value:'JHBANK',
        name:'金华银行'
    },
    {
        value:'BOCY',
        name:'朝阳银行'
    },
    {
        value:'LSBC',
        name:'临商银行'
    },
    {
        value:'BSB',
        name:'包商银行'
    },
    {
        value:'LZYH',
        name:'兰州银行'
    },
    {
        value:'BOZK',
        name:'周口银行'
    },
    {
        value:'DZBANK',
        name:'德州银行'
    },
    {
        value:'SCCB',
        name:'三门峡银行'
    },
    {
        value:'AYCB',
        name:'安阳银行'
    },
    {
        value:'ARCU',
        name:'安徽省农村信用社'
    },
    {
        value:'HURCB',
        name:'湖北省农村信用社'
    },
    {
        value:'HNRCC',
        name:'湖南省农村信用社'
    },
    {
        value:'NYNB',
        name:'广东南粤银行'
    },
    {
        value:'LYBANK',
        name:'洛阳银行'
    },
    {
        value:'NHQS',
        name:'农信银清算中心'
    },
    {
        value:'CBBQS',
        name:'城市商业银行资金清算中心'
    }
];